import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts and .netlify/ are generated by Next/Netlify tooling, not source.
  { ignores: [".next/**", ".netlify/**", "next-env.d.ts", "artifacts/**"] },
  {
    files: ["src/frontend/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/backend/*", "@/repositories/*", "@/domain/*"],
              message: "Frontend code may import only frontend modules and browser-safe shared contracts.",
            },
          ],
          paths: [
            { name: "server-only", message: "Frontend modules cannot import server-only code." },
          ],
        },
      ],
    },
  },
  {
    files: ["src/shared/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/frontend/*", "@/backend/*", "@/app/*"],
              message: "Shared contracts must remain independent of application layers.",
            },
          ],
        },
      ],
    },
  },
];
export default config;
