import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts and .netlify/ are generated by Next/Netlify tooling, not source.
  { ignores: [".next/**", ".netlify/**", "next-env.d.ts", "coverage/**", "artifacts/**"] },
];
export default config;
