"use client";
import { useState } from "react";
import { MeetingContentSchema, type Meeting, type VoteResult } from "@/shared/types";

const results: VoteResult[] = ["yes", "no", "abstain", "unresolved"];

export function MeetingEditor({ meeting, save, cancel, busy }: { meeting: Meeting; save: (content: Pick<Meeting,"minutes"|"attendees"|"motions">) => void; cancel: () => void; busy: boolean }) {
  const [draft,setDraft]=useState(()=>structuredClone({minutes:meeting.minutes,attendees:meeting.attendees,motions:meeting.motions}));
  const [error,setError]=useState("");
  const submit=()=>{const parsed=MeetingContentSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Review the meeting content before saving.");return;}save(parsed.data);};
  return <div className="space-y-5" aria-label="Edit meeting content">
    <section><h2 className="font-semibold">Minutes</h2>{draft.minutes.map((s,i)=><div className="mt-2 grid gap-2" key={s.id}><input aria-label={`Minutes heading ${i+1}`} className="input input-bordered input-sm" value={s.heading} onChange={e=>setDraft(d=>({...d,minutes:d.minutes.map((x,n)=>n===i?{...x,heading:e.target.value}:x)}))}/><textarea aria-label={`Minutes body ${i+1}`} className="textarea textarea-bordered" value={s.body} onChange={e=>setDraft(d=>({...d,minutes:d.minutes.map((x,n)=>n===i?{...x,body:e.target.value}:x)}))}/></div>)}</section>
    <section><h2 className="font-semibold">Attendance</h2>{draft.attendees.map((a,i)=><label className="mt-2 flex items-center gap-2" key={a.memberId}><input className="checkbox checkbox-sm" type="checkbox" checked={a.present} onChange={e=>setDraft(d=>({...d,attendees:d.attendees.map((x,n)=>n===i?{...x,present:e.target.checked}:x)}))}/><input aria-label={`Attendee ${i+1}`} className="input input-bordered input-sm flex-1" value={a.name} onChange={e=>setDraft(d=>({...d,attendees:d.attendees.map((x,n)=>n===i?{...x,name:e.target.value}:x)}))}/></label>)}</section>
    <section><h2 className="font-semibold">Motions and votes</h2>{draft.motions.map((m,i)=><div className="card mt-2 border border-base-300" key={m.id}><div className="card-body p-4"><input aria-label={`Motion ${i+1}`} className="input input-bordered input-sm" value={m.title} onChange={e=>setDraft(d=>({...d,motions:d.motions.map((x,n)=>n===i?{...x,title:e.target.value}:x)}))}/><div className="grid gap-2 sm:grid-cols-2"><input aria-label={`Moved by ${i+1}`} className="input input-bordered input-sm" value={m.movedBy} onChange={e=>setDraft(d=>({...d,motions:d.motions.map((x,n)=>n===i?{...x,movedBy:e.target.value}:x)}))}/><input aria-label={`Seconded by ${i+1}`} className="input input-bordered input-sm" value={m.secondedBy??""} onChange={e=>setDraft(d=>({...d,motions:d.motions.map((x,n)=>n===i?{...x,secondedBy:e.target.value||null}:x)}))}/></div>{m.votes.map((v,j)=><label className="flex items-center justify-between gap-2 text-sm" key={v.memberId}><span>{v.memberName}</span><select aria-label={`${v.memberName} vote`} className="select select-bordered select-sm" value={v.result} onChange={e=>setDraft(d=>({...d,motions:d.motions.map((x,n)=>n===i?{...x,votes:x.votes.map((vote,k)=>k===j?{...vote,result:e.target.value as VoteResult}:vote)}:x)}))}>{results.map(r=><option key={r}>{r}</option>)}</select></label>)}</div></div>)}</section>
    <div role="note" className="alert alert-info"><span>Transcript is read-only and is never changed by manual editing.</span></div>{error&&<div role="alert" className="alert alert-error"><span>{error}</span></div>}
    <div className="flex justify-end gap-2"><button className="btn btn-ghost btn-sm" onClick={cancel}>Cancel</button><button className="btn btn-primary btn-sm" disabled={busy} onClick={submit}>Save changes</button></div>
  </div>;
}
